# Generated by Django 3.2.6 on 2021-08-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210810_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='permalink',
            field=models.CharField(default='test', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
